### ISSUE TITLE
Progress of status of conversion

### ISSUE THREAD

**Issue by luiscajl** [luiscajl/VideoTranscoding-Backend#6]

**Comment by luiscajl** [comment]
The generalMatcher Not working properly

**Comment by luiscajl** [comment]
Exception in thread "pool-3-thread-4" java.lang.NumberFormatException: For input string: ""
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.base/java.lang.Integer.parseInt(Integer.java:662)
	at java.base/java.lang.Integer.parseInt(Integer.java:770)
	at es.urjc.videotranscoding.core.impl.StreamGobbler.getDifference(StreamGobbler.java:121)
	at es.urjc.videotranscoding.core.impl.StreamGobbler.run(StreamGobbler.java:76)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.base/java.lang.Thread.run(Thread.java:844)
